#[cfg(feature = "imap")]
pub mod imap;
#[cfg(feature = "jmap")]
pub mod jmap;
#[cfg(feature = "m2dir")]
pub mod m2dir;
#[cfg(feature = "maildir")]
pub mod maildir;
#[cfg(feature = "smtp")]
pub mod smtp;
